// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/accounting/{username}": {
            "get": {
                "description": "Get a specific accounting record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounting"
                ],
                "summary": "Get a specific accounting record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of the accounting record",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data of the accounting record"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            }
        },
        "/api/groups": {
            "get": {
                "description": "Get all Group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Get all Group",
                "responses": {
                    "200": {
                        "description": "List of all Group"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "post": {
                "description": "Add Group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Add Group",
                "parameters": [
                    {
                        "description": "Group data",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Radgroupreply"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Group added successfully"
                    },
                    "500": {
                        "description": "Error Group not added successfully"
                    }
                }
            }
        },
        "/api/groups/{groupname}": {
            "get": {
                "description": "Get a specific Group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Get a specific Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Groupname of the Group",
                        "name": "groupname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data of the Group"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "delete": {
                "description": "Delete Group",
                "tags": [
                    "Group"
                ],
                "summary": "Delete Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Groupname of the group to delete",
                        "name": "groupname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Group deleted successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "patch": {
                "description": "Update a Group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Update a Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Groupname of the Group to update",
                        "name": "groupname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data to update the Group",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Radgroupreply"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Group updated successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            }
        },
        "/api/nas": {
            "get": {
                "description": "Get all NAS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NAS"
                ],
                "summary": "Get all NAS",
                "responses": {
                    "200": {
                        "description": "List of all NAS"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "post": {
                "description": "Add NAS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NAS"
                ],
                "summary": "Add NAS",
                "parameters": [
                    {
                        "description": "NAS data",
                        "name": "nas",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Nas"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "NAS added successfully"
                    },
                    "500": {
                        "description": "Error NAS not added successfully"
                    }
                }
            }
        },
        "/api/nas/{nasname}": {
            "get": {
                "description": "Get a specific NAS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NAS"
                ],
                "summary": "Get a specific NAS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nasname of the NAS",
                        "name": "nasname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data of the NAS"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "delete": {
                "description": "Delete NAS",
                "tags": [
                    "NAS"
                ],
                "summary": "Delete NAS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nasname of the NAS to delete",
                        "name": "nasname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Nas deleted successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "patch": {
                "description": "Update a NAS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NAS"
                ],
                "summary": "Update a NAS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nasname of the NAS to update",
                        "name": "nasname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data to update the NAS",
                        "name": "nas",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Nas"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Nas updated successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "description": "Get all radius users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all radius users",
                "responses": {
                    "200": {
                        "description": "List of all user"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "post": {
                "description": "Create a new Radius user with radcheck and associated radreply options.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new Radius user",
                "parameters": [
                    {
                        "description": "New Radius user data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Radcheck"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User added successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            }
        },
        "/api/users/{username}": {
            "get": {
                "description": "Get specific radius user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get specific radius user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of radius user",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "delete": {
                "description": "Delete radius user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete radius user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of radius user",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "patch": {
                "description": "Update radius user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update radius user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of radius user",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Radius user data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Radcheck"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User uptaded successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            }
        },
        "/api/users/{username}/options/{optionname}": {
            "delete": {
                "description": "Delete option of radius user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete option of radius user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of radius user",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Radius user option data",
                        "name": "option",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Radreply"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Option user deleted successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Nas": {
            "type": "object",
            "properties": {
                "Community": {
                    "type": "string"
                },
                "Description": {
                    "type": "string"
                },
                "Ports": {
                    "type": "integer"
                },
                "Secret": {
                    "type": "string"
                },
                "Server": {
                    "type": "string"
                },
                "Shortname": {
                    "type": "string"
                },
                "Type": {
                    "type": "string"
                },
                "Username": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.Radcheck": {
            "type": "object",
            "properties": {
                "Attribute": {
                    "type": "string"
                },
                "Groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Radusergroup"
                    }
                },
                "Options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Radreply"
                    }
                },
                "Username": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.Radgroupreply": {
            "type": "object",
            "properties": {
                "Attribute": {
                    "type": "string"
                },
                "Groupname": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.Radreply": {
            "type": "object",
            "properties": {
                "Attribute": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.Radusergroup": {
            "type": "object",
            "properties": {
                "Groupname": {
                    "type": "string"
                },
                "Priority": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Radius API",
	Description:      "API for managing FreeRADIUS users and NAS devices",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
