// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/nas": {
            "get": {
                "description": "Get all NAS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NAS"
                ],
                "summary": "Get all NAS",
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "post": {
                "description": "Add NAS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NAS"
                ],
                "summary": "Add NAS",
                "parameters": [
                    {
                        "description": "New NAS data",
                        "name": "nas",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Nas"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "NAS added successfully"
                    },
                    "500": {
                        "description": "Failure insert data into dabasase"
                    }
                }
            }
        },
        "/nas/{username}": {
            "get": {
                "description": "Get a specific NAS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NAS"
                ],
                "summary": "Get a specific NAS",
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "put": {
                "description": "Update a NAS",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NAS"
                ],
                "summary": "Update a NAS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nasname of the NAS to update",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data to update the NAS",
                        "name": "nas",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Nas"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Nas updated successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            },
            "delete": {
                "description": "Delete NAS",
                "tags": [
                    "NAS"
                ],
                "summary": "Delete NAS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nasname of the NAS to delete",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Nas deleted successfully"
                    },
                    "500": {
                        "description": "Error"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Récupère la liste complète des utilisateurs (radcheck) avec leurs radreply associées.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Récupérer tous les utilisateurs Radius",
                "responses": {
                    "200": {
                        "description": "Liste des utilisateurs complète"
                    },
                    "500": {
                        "description": "Erreur interne du serveur"
                    }
                }
            },
            "post": {
                "description": "Create a new Radius user with radcheck and associated radreply options.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new Radius user",
                "parameters": [
                    {
                        "description": "New Radius user data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Radcheck"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User added successfully"
                    },
                    "400": {
                        "description": "Erreur ajout user"
                    }
                }
            }
        },
        "/users/{username}": {
            "get": {
                "description": "Récupère les détails d'un utilisateur spécifique (radcheck) avec ses radreply associées.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Récupérer un utilisateur Radius spécifique",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur du Radius",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Détails de l'utilisateur"
                    },
                    "500": {
                        "description": "Erreur interne du serveur"
                    }
                }
            },
            "delete": {
                "description": "Supprime un utilisateur spécifique (radcheck) et ses radreply associées.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Supprimer un utilisateur Radius",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur du Radius à supprimer",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Utilisateur supprimé avec succès"
                    },
                    "500": {
                        "description": "Erreur interne du serveur"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Nas": {
            "type": "object",
            "properties": {
                "community": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nasname": {
                    "type": "string"
                },
                "ports": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "server": {
                    "type": "string"
                },
                "shortname": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.Radcheck": {
            "type": "object",
            "properties": {
                "Options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Radreply"
                    }
                },
                "attribute": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.Radreply": {
            "type": "object",
            "properties": {
                "Attribute": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Radius API",
	Description:      "API for managing FreeRADIUS users and NAS devices",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
