// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/nas": {
            "get": {
                "description": "Récupère la liste complète de tous les NAS configurés",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NAS"
                ],
                "summary": "Récupérer tous les NAS Radius",
                "responses": {
                    "200": {
                        "description": "Liste des NAS récupérée avec succès",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Nas"
                            }
                        }
                    },
                    "500": {
                        "description": "Erreur serveur interne",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Nas": {
            "type": "object",
            "properties": {
                "community": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nasname": {
                    "type": "string"
                },
                "ports": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "server": {
                    "type": "string"
                },
                "shortname": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.1.240:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Radius API",
	Description:      "API pour la gestion des utilisateurs et des NAS Radius.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
