basePath: /
definitions:
  models.Nas:
    properties:
      community:
        type: string
      description:
        type: string
      id:
        type: integer
      nasname:
        type: string
      ports:
        type: integer
      secret:
        type: string
      server:
        type: string
      shortname:
        type: string
      type:
        type: string
    type: object
  models.Radcheck:
    properties:
      Options:
        items:
          $ref: '#/definitions/models.Radreply'
        type: array
      attribute:
        type: string
      id:
        type: integer
      username:
        type: string
      value:
        type: string
    type: object
  models.Radreply:
    properties:
      Attribute:
        type: string
      Value:
        type: string
    type: object
info:
  contact: {}
  description: API for managing FreeRADIUS users and NAS devices
  title: Radius API
  version: "1.0"
paths:
  /nas:
    get:
      consumes:
      - application/json
      description: Get all NAS
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Error
      summary: Get all NAS
      tags:
      - NAS
    post:
      consumes:
      - application/json
      description: Add NAS
      parameters:
      - description: New NAS data
        in: body
        name: nas
        required: true
        schema:
          $ref: '#/definitions/models.Nas'
      produces:
      - application/json
      responses:
        "200":
          description: NAS added successfully
        "500":
          description: Failure insert data into dabasase
      summary: Add NAS
      tags:
      - NAS
  /nas/{username}:
    delete:
      description: Delete NAS
      parameters:
      - description: Nasname of the NAS to delete
        in: path
        name: username
        required: true
        type: string
      responses:
        "200":
          description: Nas deleted successfully
        "500":
          description: Error
      summary: Delete NAS
      tags:
      - NAS
    get:
      consumes:
      - application/json
      description: Get a specific NAS
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Error
      summary: Get a specific NAS
      tags:
      - NAS
    patch:
      consumes:
      - application/json
      description: Update a NAS
      parameters:
      - description: Nasname of the NAS to update
        in: path
        name: username
        required: true
        type: string
      - description: Data to update the NAS
        in: body
        name: nas
        required: true
        schema:
          $ref: '#/definitions/models.Nas'
      produces:
      - application/json
      responses:
        "200":
          description: Nas updated successfully
        "500":
          description: Error
      summary: Update a NAS
      tags:
      - NAS
  /users:
    get:
      consumes:
      - application/json
      description: Get all radius users
      produces:
      - application/json
      responses:
        "200":
          description: List of all user
        "500":
          description: Error
      summary: Get all radius users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new Radius user with radcheck and associated radreply
        options.
      parameters:
      - description: New Radius user data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.Radcheck'
      produces:
      - application/json
      responses:
        "200":
          description: User added successfully
        "500":
          description: Error
      summary: Create a new Radius user
      tags:
      - users
  /users/{username}:
    delete:
      consumes:
      - application/json
      description: Delete radius user
      parameters:
      - description: Username of radius user
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User deleted successfully
        "500":
          description: Error
      summary: Delete radius user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get specific radius user
      parameters:
      - description: Nom d'utilisateur du Radius
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Error
      summary: Get specific radius user
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update radius user
      parameters:
      - description: Username of radius user
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User uptaded successfully
        "500":
          description: Error
      summary: Update radius user
      tags:
      - users
  /users/option/{username}:
    delete:
      consumes:
      - application/json
      description: Delete option of radius user
      parameters:
      - description: Username of radius user
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Option user deleted successfully
        "500":
          description: Error
      summary: Delete option of radius user
      tags:
      - users
swagger: "2.0"
